Update installer-full

diff --git a/installer-full b/installer-full
--- a/installer-full
+++ b/installer-full
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if [ $EUID -ne 0 ]; then
+    echo "ERROR: This tool must be run as root"
+    exit 1
+fi
+
 #------------------------------------------------#
 #                 Pre-requisites                 #
 #------------------------------------------------#
